### ISSUE TITLE
Staticky results

### ISSUE THREAD

**Issue by jonkatz** [craigsdennis/genai-phone-call#1]
Hey, thank you for the helpful starter! I'm getting a lot of static, however, and wondering why that might be.  Are you experiencing it as well?

**Comment by avinash403** [comment]
I face the same

**Comment by craigsdennis** [comment]
I would love to figure that out too! 

I think it is surrounding this line: https://github.com/craigsdennis/genai-phone-call/blob/main/tts-service.js#L36

@elevenlabs any idea?

**Comment by craigsdennis** [comment]
I tried some more settings which sounds better but I think is still clipping.

Trying to follow [this documentation](https://audioaudit.io/articles/podcast/sample-width)

**Comment by HAJEKEL** [comment]
I also experience the noise, the people here seemed to have fixed it: https://stackoverflow.com/questions/64003753/encode-linear16-audio-to-twilio-media-audio-x-mulaw-nodejs, but when I checked your code you already seemed to have implemented that. I tried your improved settings, the volume is louder indeed but the noise is still there. I'll try to help you find a solution:) I'll check out the documentation that you shared.

**Comment by HAJEKEL** [comment]
Ok guys, I have tried a lot of things but I can't figure it out.. 
One thing I discovered:
      wav.toSampleRate(8000); //Increasing slows the audio down, decreasing speeds the audio up (increase->lower freq) (decrease -> higher freq)
But yeah, wish I found the solution.. Really hope someone can fix it because that would help me a lot:)

**Comment by HAJEKEL** [comment]
I found this: It tells us to not use the mp3 format from elevenlabs. https://support.twilio.com/hc/en-us/articles/223180588-Best-Practices-for-Audio-Recordings

**Comment by craigsdennis** [comment]
Woop! Got it working! I was using treating the `response.arrayBuffer` as an unsigned integer array, but actually it's signed.

https://github.com/craigsdennis/genai-phone-call/commit/c9eeae03b4ff0f96015d9ae94e7bbc8eb3c67661

**Comment by jonkatz** [comment]
Awesome!  Thanks!!!

**Comment by HAJEKEL** [comment]
Nice!!!:) Thank you very much:) Amazing!!!
